### ISSUE TITLE
is zkLLVM a zkVM?

### ISSUE THREAD

**Issue by alexanderlhicks** [rkdud007/awesome-zkvm#12]
Hi!

Looking at the zkLLM repository it seems to specifically argue that it is not a zkVM and, instead, that it makes zkVMs redundant. On this basis, should they be included in the list of zkVMs?
I don't have a strong opinion either, but it could be useful to have a clearer definition of what counts as a zkVM for the purpose of this repository.

**Comment by rkdud007** [comment]
Hi 
Actually thats valid point - initially haven't added cus by formal definition it is not - 

I tentatively added from some resources included zkLLVM as zkVM (related) map, but for this list it make sense to skip it or have it on relevant list 

Wdyt?

**Comment by rkdud007** [comment]
Saw the table - sure we can move out it from the table and have only zkVM projects on table for PR :)
