### ISSUE TITLE
Add zkvm from scratch articles/repo

### ISSUE THREAD

**Issue by rkdud007** [rkdud007/awesome-zkvm#2]
Have some great educational tutorial series for build own tiny zkvm e.g Alan's brainfuck stark vm tutorial, risc0 zk vm tutorial etc( didnt recall atm ) - will add tmrw

**Comment by gerceboss** [comment]
Sounds great! But I couldn't find any articles related to building a tiny zkvm from scratch rather than using some external crate. 

Would appreciate if you can suggest and add some in the repo @rkdud007

**Comment by rkdud007** [comment]
Umm https://github.com/rkdud007/brainfuck-zkvm mainly thinking of tutorial attached this repo read me, not sure if theres any riscv based tutorials thought i saw risc0 had before somewhere cannot find atm - ye will update more

**Comment by rkdud007** [comment]
added #3
