### ISSUE TITLE
zkVMs for consideration

### ISSUE THREAD

**Issue by JustinDrake** [rkdud007/awesome-zkvm#6]
zkVMs for consideration to the awesome-zkvm list :)

* ceno (see [here](https://github.com/privacy-scaling-explorations/ceno) and [here](https://github.com/scroll-tech/ceno)
* Zorp (see talk [here](https://www.youtube.com/watch?v=zD45V6GAD00))
* zkOS (referenced in [this tweet](https://x.com/dhruvbodani/status/1779831169493717325))
* Sphinx (see [here](https://github.com/argumentcomputer/sphinx))

**Comment by rkdud007** [comment]
thanks for the suggestion - if u don't mind I'd like to add u on co-author on #7 merging :)

- [added] ceno, scroll version
- [added] Zorp couldn't found opensource project so added talk as resource
- zkOS couldn't found opensource project on matterlabs repo
- sphinx already on list

**Comment by JustinDrake** [comment]
Perfect! I asked Logan Allen from Zorp who said it will be released under the MIT license shortly.

**Comment by JustinDrake** [comment]
Michael Dong from Brevis and Celer is working on a RISC-V zkVM called Pico using circle STARKs.

**Comment by JustinDrake** [comment]
https://github.com/armanthepythonguy/Useless-ZKVM

**Comment by rkdud007** [comment]
https://blog.axiom.xyz/openvm/

**Comment by rkdud007** [comment]
couldn't found repo/announcement on zkOS or Pico 

Nocks https://github.com/zorp-corp/nockapp found but hard to see precompile/continuation status

is there way to get more info on ^?

**Comment by JustinDrake** [comment]
> couldn't found repo/announcement on zkOS or Pico

Those are zkVMs to expect—I don't know of any of the three being open source yet :)

**Comment by JustinDrake** [comment]
Another zkVM! https://x.com/SebastienGllmt/status/1874799782491037975

* zkOS by Matter Labs (source: Anthony Rose)
* Nock by Zorp (source: Logan Allen)
* Pico by Brevis (source: Michael Dong)
* Starstream by Paima (source: Sebastien Guillemot)
